### ISSUE TITLE
The order of matrix multiplication is different in ign-math4 and ign-math6 

### ISSUE THREAD

**Issue by erdisayar** [ignitionrobotics/ign-math#190] opened 2021-02-11 17:00 UTC
Hello,
I tested matrix multiplication operator in both **math4** and **math6** library and I obtained 2 different results.
![image](https://user-images.githubusercontent.com/44807161/107669457-09c71880-6c92-11eb-8928-72ed7a591416.png)
![image](https://user-images.githubusercontent.com/44807161/107669332-e9975980-6c91-11eb-8863-ad3c0a9fd9e1.png)

The the first test is in Gazebo9(Ubuntu 18.04) using math4 library. Here is my result.
![image](https://user-images.githubusercontent.com/44807161/107669539-25caba00-6c92-11eb-9ae0-1888022758e0.png)

**I think it is wrong because it is not the calculation of MatrixA x MatrixB instead MatrixB x Matrix A**. However the intention is MatrixA x Matrix B

If I test the same code in Gazebo11(Ubuntu 20) using math6 library. Here is the result
![image](https://user-images.githubusercontent.com/44807161/107669907-84903380-6c92-11eb-92a1-4547b54eae00.png)
The result is correct.

**summary from my investigation is(maybe I am wrong)**

If I want to calculate the matrix multiplication of AB, 
- **math4 library calculates BA instead of AB**
- **math6 library calculates AB**

Here is the code in the picture.
```
std::cout << "Matrix A " << std::endl;
WORLD_POSE MatrixA = WORLD_POSE(1, 0, 0, 0, 0, 0);
std::cout << "Matrix A Pos:" << MatrixA.Pos() << std::endl;
std::cout << "Matrix A Rot:" << MatrixA.Rot() << std::endl;
std::cout << "Matrix B" << std::endl;
WORLD_POSE MatrixB = WORLD_POSE(0, 0, 0, 0, 0, 1);
std::cout << "Matrix B Pos:" << MatrixB.Pos() << std::endl;
std::cout << "Matrix B Rot:" << MatrixB.Rot() << std::endl;
std::cout << "----------" << std::endl;
std::cout << "Matrix C = A * B " << std::endl;

WORLD_POSE MatrixC = MatrixA * MatrixB;
std::cout << "Matrix C Pos:" << MatrixC.Pos() << std::endl;
std::cout << "Matrix C Pos:" << MatrixC.Rot() << std::endl;
std::cout << "----------" << std::endl;
```

**Comment by erdisayar** [comment] 2021-02-11 17:04
Here is the image for comparison 
![image](https://user-images.githubusercontent.com/44807161/107670902-83abd180-6c93-11eb-88ba-0fb2b629df04.png)

**Comment by chapulina** [comment] 2021-02-11 18:31
I wrote a quick test to check Matrix4 multiplication in #191 and I couldn't see any inconsistencies between `ign-math4` and `ign-math6`.

Note that your example is using `ignition::math::Pose3d`, not `ignition::math::Matrix4d`. The behaviour of the `*` operator for `Pose3` has been changed (fixed) from `ign-math4` to `ign-math5`, as documented on the [migration guide](https://github.com/ignitionrobotics/ign-math/blob/ign-math6/Migration.md#breaking-changes). I believe that's the underlying reason for what you're seeing.

**Comment by erdisayar** [comment] 2021-02-11 18:44
Thanks for enlightening the issue. What kind of behavior did you implemented before (for ign-math4) ? and what was the its logic?

As you see from my calculations for `ign-math4` , the behavior I saw is basically same as  reverse order matrix multiplication for `ignition::math::Pose3d.`  

In other words, What is the use case before?

**Comment by scpeters** [comment] 2021-02-11 18:50
I don't know why it was this way. You can read more of the history in https://github.com/ignitionrobotics/ign-math/issues/60 and [bitbucket PR 301](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-math/pull-requests/301/page/1). I'm closing since this is not a bug, but feel free to continue the discussion if you like

**Closed by scpeters** 2021-02-11 18:50 UTC
Labels: bug
