### ISSUE TITLE
 Could not find a package configuration file provided by "ignition-cmake0"

### ISSUE THREAD

**Issue by Anusha-jain-h-c** [ignitionrobotics/ign-math#138] opened 2020-07-19 07:30 UTC
I am installing gazebo on windows using tutorial http://gazebosim.org/tutorials?tut=install_on_windows&cat=install
i encountered an error while i am at step 9.. as i am new i request for a help.. as to how can i make changes using the command prompt ...

```
C:\Users\abdhi>git clone https://github.com/ignitionrobotics/ign-math -b ign-math4
Cloning into 'ign-math'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (24/24), done.
Rremote: Total 14834 (delta 9), reused 12 (delta 5), pack-reused 14805eceiving objects:  87% (12906/14834), 8.54 MiB | 8Receiving objects: 100% (14834/14834), 9.78 MiB | 140.00 KiB/s, done.
Resolving deltas:  97% (10328/10636)
Resolving deltas: 100% (10636/10636), done.

C:\Users\abdhi>cd ign-math

C:\Users\abdhi\ign-math>.\configure

C:\Users\abdhi\ign-math>call  :install_ign_project ign-cmake ign-cmake0
The system cannot find the batch label specified - install_ign_project
Configuring for build type Release

C:\Users\abdhi\ign-math>cd /d C:\Users\abdhi\ign-math\

C:\Users\abdhi\ign-math>md build

C:\Users\abdhi\ign-math>cd build

C:\Users\abdhi\ign-math\build>cmake .. -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX=""install\Release"" -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING:BOOL=False
-- The C compiler identification is MSVC 19.26.28806.0
-- The CXX compiler identification is MSVC 19.26.28806.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx86/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx86/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "Findignition-cmake0.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-cmake0", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-cmake0"
  (requested version 0.3.0) with any of the following names:

    ignition-cmake0Config.cmake
    ignition-cmake0-config.cmake

  Add the installation prefix of "ignition-cmake0" to CMAKE_PREFIX_PATH or
  set "ignition-cmake0_DIR" to a directory containing one of the above files.
  If "ignition-cmake0" provides a separate development package or SDK, be
  sure it has been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by chapulina** [comment] 2020-07-20 18:51
This issue is a duplicate of https://github.com/ignitionrobotics/ign-msgs/issues/72, so I'll close this one since that one already has some conversation going.

**Closed** 2020-07-20 18:51 UTC
